### ISSUE TITLE
AWS Console change broke aws-sso-account-alert.js  - proposed fix

### ISSUE THREAD

**Issue by seangreathouse** [mhlabs/aws-console-tampermonkey#4]
Replace  
`var account = document.querySelector("span[data-testid='aws-my-account-details']").innerText;` 
With
`var account = document.querySelector("div[data-testid='account-detail-menu'] div div span:nth-child(2)").innerText;`

**Comment by mohamed-haidara-ai71** [comment]
Thanks for the fix. Works like a charm

**Comment by seangreathouse-psbl** [comment]
Good.
Credit to @tlee32 for the work.

**Comment by ljacobsson** [comment]
Sorry for the slow reaction :-)

Thanks @seangreathouse !

I'll update the code with your suggestion :raised_hands: Works great on my machine too
